export const ENEMIES = [
  {
    id: "lobo-espectral",
    name: "Lobo Espectral",
    element: "vendaval",
    tipo: "sabio",
    personality: "Rápido e frágil: morde antes de morrer.",
    hpMult: 0.8,
    atkMult: 1.0,
    defMult: 0.6,
    manaMult: 0.5,
    skills: ["rajada-cortante"],
    canUseItems: false,
  },
  {
    id: "esqueleto-guardiao",
    name: "Esqueleto Guardião",
    element: "rocha",
    tipo: "mecanico",
    personality: "Lento e ossudo: aguenta muito, bate pouco.",
    hpMult: 1.4,
    atkMult: 0.7,
    defMult: 1.0,
    manaMult: 0.5,
    skills: ["pele-de-pedra"],
    canUseItems: false,
  },
  {
    id: "cavaleiro-cripta",
    name: "Cavaleiro da Cripta",
    boss: true,
    element: "rocha",
    tipo: "mecanico",
    personality: "Guardião final do cemitério, armadura forjada em ossos.",
    hpMult: 2.0,
    atkMult: 1.4,
    defMult: 1.3,
    manaMult: 1.0,
    skills: ["pele-de-pedra", "queda-de-rocha"],
    canUseItems: false,
  },
  {
    id: "golem-gelo",
    name: "Golem de Gelo",
    element: "mare",
    tipo: "mecanico",
    personality: "Muralha viva: defesa alta, passos lentos.",
    hpMult: 1.4,
    atkMult: 0.9,
    defMult: 1.3,
    manaMult: 1.2,
    skills: ["jato-congelante"],
    canUseItems: true,
  },
  {
    id: "arpia-glacial",
    name: "Arpia Glacial",
    element: "vendaval",
    tipo: "sabio",
    personality: "Veloz e cortante: difícil de acertar.",
    hpMult: 0.8,
    atkMult: 1.3,
    defMult: 0.8,
    manaMult: 1.3,
    skills: ["rajada-cortante"],
    canUseItems: true,
  },
  {
    id: "senhor-geada",
    name: "Senhor da Geada",
    boss: true,
    element: "mare",
    tipo: "sabio",
    personality: "A fúria do inverno encarnada.",
    hpMult: 2.1,
    atkMult: 1.5,
    defMult: 1.3,
    manaMult: 1.6,
    skills: ["jato-congelante", "onda-congelante"],
    canUseItems: true,
  },
  {
    id: "diabrete-igneo",
    name: "Diabrete Ígneo",
    element: "magma",
    tipo: "infernal",
    personality: "Pequeno e incendiário: muito dano, corpo frágil.",
    hpMult: 0.9,
    atkMult: 1.4,
    defMult: 0.9,
    manaMult: 1.3,
    skills: ["bola-de-fogo"],
    canUseItems: true,
  },
  {
    id: "bruto-magma",
    name: "Bruto de Magma",
    element: "rocha",
    tipo: "infernal",
    personality: "Colosso lento de pedra e fogo.",
    hpMult: 1.5,
    atkMult: 1.1,
    defMult: 1.2,
    manaMult: 1.0,
    skills: ["queda-de-rocha", "pele-de-pedra"],
    canUseItems: true,
  },
  {
    id: "rei-demonio",
    name: "Rei Demônio",
    boss: true,
    element: "magma",
    tipo: "infernal",
    personality: "Senhor da fortaleza, coroa de brasas.",
    hpMult: 2.0,
    atkMult: 1.6,
    defMult: 1.2,
    manaMult: 1.8,
    skills: ["bola-de-fogo", "erupcao"],
    canUseItems: true,
  },
];

export const TUTORIAL_ENEMIES = [
  {
    id: "lobo-espectral-1",
    name: "Lobo Espectral",
    element: "vendaval",
    tipo: "sabio",
    personality: "Rápido e frágil: morde antes de morrer.",
    skills: [],
    canUseItems: false,
    tip: "Role o dado e use Atacar para causar dano.",
    tipMechanic: "attack",
    stats: {
      maxHp: 2,
      atk: 1,
      def: 0,
      mana: 2,
      goldBase: 2,
      goldExtra: 2,
      xpBase: 2,
      xpExtra: 2,
    },
  },
  {
    id: "esqueleto-guardiao-1",
    name: "Esqueleto Guardião",
    element: "rocha",
    tipo: "mecanico",
    personality: "Lento e ossudo: aguenta muito, bate pouco.",
    skills: [],
    canUseItems: false,
    tip: "Use Defender para reduzir o dano pela metade.",
    tipMechanic: "defend",
    stats: {
      maxHp: 3,
      atk: 1,
      def: 0,
      mana: 2,
      goldBase: 2,
      goldExtra: 2,
      xpBase: 2,
      xpExtra: 2,
    },
  },
  {
    id: "golem-gelo-1",
    name: "Golem de Gelo",
    element: "mare",
    tipo: "mecanico",
    personality: "Muralha viva: defesa alta, passos lentos.",
    skills: [],
    canUseItems: false,
    tip: "Ao levar dano, sua Fúria enche. Cheia, use o Especial.",
    tipMechanic: "special",
    stats: {
      maxHp: 3,
      atk: 1,
      def: 1,
      mana: 2,
      goldBase: 2,
      goldExtra: 2,
      xpBase: 2,
      xpExtra: 2,
    },
  },
  {
    id: "arpia-glacial-1",
    name: "Arpia Glacial",
    element: "vendaval",
    tipo: "sabio",
    personality: "Veloz e cortante: difícil de acertar.",
    skills: [],
    canUseItems: false,
    tip: "Vencer dá ouro e XP — com XP você sobe de nível.",
    tipMechanic: "victory",
    stats: {
      maxHp: 4,
      atk: 2,
      def: 0,
      mana: 2,
      goldBase: 3,
      goldExtra: 2,
      xpBase: 3,
      xpExtra: 2,
    },
  },
  {
    id: "diabrete-igneo-1",
    name: "Diabrete Ígneo",
    element: "magma",
    tipo: "infernal",
    personality: "Pequeno e incendiário: muito dano, corpo frágil.",
    skills: [],
    canUseItems: false,
    tip: "Cada região tem um chefe. Vença mais para enfrentá-lo!",
    tipMechanic: "victory",
    stats: {
      maxHp: 5,
      atk: 2,
      def: 1,
      mana: 2,
      goldBase: 3,
      goldExtra: 2,
      xpBase: 3,
      xpExtra: 2,
    },
  },
];

export function getEnemy(id) {
  return ENEMIES.find((e) => e.id === id) || null;
}

export function getTutorialEnemy(step) {
  return TUTORIAL_ENEMIES[step] || null;
}