import {
  Flame,
  Bomb,
  Sun,
  FlameKindling,
  HeartPulse,
  ShieldPlus,
  Shield,
  Sparkle,
  Snowflake,
  CloudSnow,
  CloudFog,
  ThermometerSnowflake,
} from "lucide-react";

export const SKILL_BRANCHES = {
  sombrio: { key: "sombrio", label: "Sombrio", tagline: "Ofensa" },
  sagrado: { key: "sagrado", label: "Sagrado", tagline: "Suporte" },
  magico: { key: "magico", label: "Mágico", tagline: "Controle" },
};

export const SKILLS = [
  {
    id: "brasa",
    name: "Brasa",
    branch: "sombrio",
    element: "magma",
    parent: null,
    levelReq: 1,
    goldCost: 5,
    manaCost: 3,
    icon: Flame,
    x: 8,
    y: 30,
    rot: -6,
    effect: { type: "damage", mult: 1.8 },
    description: "Golpe ardente de Magma. Causa 180% do dano de ataque.",
  },
  {
    id: "explosao",
    name: "Explosão",
    branch: "sombrio",
    element: "magma",
    parent: "brasa",
    levelReq: 3,
    goldCost: 15,
    manaCost: 5,
    icon: Bomb,
    x: 37,
    y: 72,
    rot: 5,
    effect: { type: "damage", mult: 2.6 },
    description: "Detonação violenta de Magma. Causa 260% do dano de ataque.",
  },
  {
    id: "meteoro",
    name: "Meteoro",
    branch: "sombrio",
    element: "magma",
    parent: "explosao",
    levelReq: 5,
    goldCost: 30,
    manaCost: 7,
    icon: Sun,
    x: 64,
    y: 34,
    rot: -4,
    effect: { type: "damage", mult: 3.5 },
    description: "Invoca fogo dos céus. Causa 350% do dano de ataque.",
  },
  {
    id: "apocalipse",
    name: "Apocalipse",
    branch: "sombrio",
    element: "magma",
    parent: "meteoro",
    levelReq: 8,
    goldCost: 60,
    manaCost: 8,
    icon: FlameKindling,
    x: 92,
    y: 68,
    rot: 6,
    effect: { type: "damage", mult: 4.5 },
    description: "O fim em chamas. Causa 450% do dano de ataque.",
  },
  {
    id: "cura",
    name: "Cura Leve",
    branch: "sagrado",
    element: "vendaval",
    parent: null,
    levelReq: 1,
    goldCost: 5,
    manaCost: 3,
    icon: HeartPulse,
    x: 8,
    y: 32,
    rot: -4,
    effect: { type: "heal", base: 2, pct: 0.25 },
    description: "Restaura parte da vida.",
  },
  {
    id: "bencao",
    name: "Bênção",
    branch: "sagrado",
    element: "vendaval",
    parent: "cura",
    levelReq: 3,
    goldCost: 15,
    manaCost: 4,
    icon: ShieldPlus,
    x: 37,
    y: 62,
    rot: 3,
    effect: { type: "shield", base: 2, defFactor: 0.5 },
    description: "Barreira sagrada absorve o próximo dano.",
  },
  {
    id: "escudo-divino",
    name: "Escudo Divino",
    branch: "sagrado",
    element: "vendaval",
    parent: "bencao",
    levelReq: 5,
    goldCost: 30,
    manaCost: 5,
    icon: Shield,
    x: 64,
    y: 34,
    rot: -5,
    effect: { type: "shield", base: 4, defFactor: 1, healFlat: 1 },
    description: "Cura 1 de vida e ergue uma grande barreira.",
  },
  {
    id: "milagre",
    name: "Milagre",
    branch: "sagrado",
    element: "vendaval",
    parent: "escudo-divino",
    levelReq: 8,
    goldCost: 60,
    manaCost: 8,
    icon: Sparkle,
    x: 92,
    y: 60,
    rot: 4,
    effect: { type: "heal", full: true },
    description: "Restaura toda a vida.",
  },
  {
    id: "lanca-gelo",
    name: "Lança de Gelo",
    branch: "magico",
    element: "mare",
    parent: null,
    levelReq: 2,
    goldCost: 10,
    manaCost: 3,
    icon: Snowflake,
    x: 8,
    y: 66,
    rot: 4,
    effect: { type: "damage", mult: 1.3, drainStamina: 3 },
    description: "Fere com Maré congelante e drena 3 de estamina do inimigo.",
  },
  {
    id: "congelar",
    name: "Congelar",
    branch: "magico",
    element: "mare",
    parent: "lanca-gelo",
    levelReq: 4,
    goldCost: 20,
    manaCost: 4,
    icon: CloudSnow,
    x: 37,
    y: 38,
    rot: -6,
    effect: { type: "stun" },
    description: "Congela o inimigo por um turno.",
  },
  {
    id: "era-glacial",
    name: "Era Glacial",
    branch: "magico",
    element: "mare",
    parent: "congelar",
    levelReq: 6,
    goldCost: 40,
    manaCost: 6,
    icon: CloudFog,
    x: 64,
    y: 24,
    rot: 5,
    effect: { type: "damage", mult: 2, drainFury: 2 },
    description: "Golpe congelante que apaga 2 de fúria inimiga.",
  },
  {
    id: "zero-absoluto",
    name: "Zero Absoluto",
    branch: "magico",
    element: "mare",
    parent: "era-glacial",
    levelReq: 8,
    goldCost: 60,
    manaCost: 8,
    icon: ThermometerSnowflake,
    x: 92,
    y: 58,
    rot: -3,
    effect: { type: "damage", mult: 2.2, stun: true },
    description: "Dano pesado e congela o inimigo por um turno.",
  },
];

export function getSkill(id) {
  return SKILLS.find((s) => s.id === id) || null;
}

export function getBranchSkills(branchKey) {
  return SKILLS.filter((s) => s.branch === branchKey);
}